jdbc.driverClassName = com.mysql.cj.jdbc.Driver

#Local
#jdbc.url = jdbc:mysql://localhost:3306/test
#jdbc.username = root
#jdbc.password = root

#EVA
jdbc.url =  jdbc:mysql://183.82.3.24:3306/EVA?noAccessToProcedureBodies=true
jdbc.username = evadevadmin
jdbc.password = evadevadmin@123
hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql = true
hibernate.format_sql = false
hibernate.hbm2ddl.auto = none
hibernate.ejb.naming_strategy = org.hibernate.cfg.ImprovedNamingStrategy
bucketName=eva-resources
s3rootfolder=application-uploads
hibernate.proc.param_null_passing=true
ELASTIC_CACHE_URL=search-eva-dev-es-mduowhe6raiuaya7wgpt7wgtbi.ap-south-1.es.amazonaws.com
ELASTIC_CACHE_PORT=443
