jdbc.connection.url =  jdbc:mysql://183.82.3.24:3306/EVA?noAccessToProcedureBodies=true&useSSL=false
jdbc.connection.username = evadevadmin
jdbc.connection.password = evadevadmin@123
hibernate.jdbc.batch_size=300