0=Pending with Employee for Adding Services
1=Pending with Employee for Submission
2=Awaiting for Approval
3=Rejected
4=Awaiting for Booking
5=Booked
6=Booking Failed
7=Ignored
8=Booking Cancelled
9=Pending
10=In Progress
11=Request Cancelled
12=Split Pnr
13=Discard
14=PNR Blocked
15=PNR Cancelled
17=Visa Awaiting Documents
18=Visa In Progress
19=Partially Booked
20=New
21=Request Acknowledged
22=Documents Under Review
23=Documents Incomplete
24=Documents Dispatched for Submission
25=Application Submitted
26=In Person Interview
27=Additional Documents asked by Consulate
28=Visa Granted
29=Visa Rejected
30=Documents Dispatched
31=Refund in Progress
32=Partial refund in Progress
33=Refunded
34=Partially Refunded
35=Partially cancelled
36=Awaiting for Processing
37=Booking In Progress
38=Booking Pending (Pending Supplier Confirmation)
39=Partially Booked
40=Pending with Employee for Booking
41=Booking Pending with Consultant
42=Pending with Bot for Booking
43=Booked Awaiting for Approval
44=Awaiting for Cancellation
45=Cancelled (Process Payment Pending)
46=Partially Cancelled
47=Awaiting for Reschedule
48=Rescheduled (Process Payment Pending)
49=Awaiting for Split PNR
50=Awaiting for SSR
51=SSR Confirmed (Process Payment Pending)
52=Pending with Consultant for Processing
53=Awaiting for Miscellaneous Request
54=Miscellaneous Request Confirmed (Process Payment Pending)
55=Pending with Consultant for Options Sharing
56=Pending with Employee for Option Selection
99=Empty Trip